spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/job-offers

job-offers:
  offers:
    offersRunOccurrence: "0 0 12 * * 6"
    http:
      client:
        config:
#          uri: http://ec2-3-127-218-34.eu-central-1.compute.amazonaws.com:5057/offers
          uri: http://ec2-3-127-218-34.eu-central-1.compute.amazonaws.com
          port: 5057
          connectionTimeout: 1000
          readTimeout: 5000

  http:
    offers:
      scheduler:
        request:
          delay: PT3H

  scheduling:
    enabled: true